### ISSUE TITLE
Settings bug

### ISSUE THREAD

**Issue by wtfliru** [damianmcclure/CryptCord#3]
Whenever I go to settings it is just blank. (new user). Thus I cannot use this plugin because it keeps disabling.

**Comment by damianmcclure** [comment]
This is a problem with BetterDiscord loading plugins before it loads the pluginutilities, please get the restartNoMore.plugin.js to fix this issue temporarily. https://github.com/Inve1951/BetterDiscordStuff/blob/master/plugins/restartNoMore.plugin.js

**Comment by damianmcclure** [comment]
Nevermind, download the newest update. It's completely fixed
